force-app/main/default/objects/Brag__c/Brag__c.object-meta.xml
<CustomObject>
    <label>Brag</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Brag Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brag__c/fields/Business_Impact__c.field-meta.xml
<CustomField>
    <fullName>Business_Impact__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Business Impact</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brag__c/fields/Date_Completed__c.field-meta.xml
<CustomField>
    <fullName>Date_Completed__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Date Completed</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Brag__c/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brag__c/fields/Technical_Complexity__c.field-meta.xml
<CustomField>
    <fullName>Technical_Complexity__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Technical Complexity</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BragAppDisplayBragsController.cls
public without sharing class BragAppDisplayBragsController {
    @AuraEnabled(Cacheable=true)
    public static List<Brag__c> getBrags() {
        return [
                SELECT Id, Title__c, Body__c, Business_Impact__c, Technical_Complexity__c, Date_Completed__c
                FROM Brag__c
                WHERE Published__c = TRUE
                ORDER BY Date_Completed__c DESC
        ];
    }
}